{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nlmixr2plot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nlmixr2plot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nlmixr2plot/nlmixr2plot_{{ version }}.tar.gz
  sha256: 1fa74dc400b3a6997ca8f65d130505a9193bb936a08a5957db46e7b1917ab7b8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-nlmixr2est
    - r-nlmixr2extra
    - r-rxode2
    - r-vpc
    - r-xgxr
  run:
    - r-base
    - r-ggplot2
    - r-nlmixr2est
    - r-nlmixr2extra
    - r-rxode2
    - r-vpc
    - r-xgxr

test:
  commands:
    - $R -e "library('nlmixr2plot')"           # [not win]
    - "\"%R%\" -e \"library('nlmixr2plot')\""  # [win]

about:
  home: https://nlmixr2.github.io/nlmixr2plot/
  dev_url: https://github.com/nlmixr2/nlmixr2plot
  license: GPL-3.0-or-later
  summary: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2'
    package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>). This package is for 'ggplot2' plotting methods for 'nlmixr2' objects.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nlmixr2plot
# Title: Nonlinear Mixed Effects Models in Population PK/PD, Plot Functions
# Version: 2.0.7
# Authors@R: c( person("Matthew", "Fidler", email="matthew.fidler@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8538-6691")), person("Bill", "Denney", email="wdenney@humanpredictions.com", role = "ctb", comment = c(ORCID = "0000-0002-5759-428X")), person("Wenping", "Wang", email="wwang8198@gmail.com", role = "aut"), person("Vipul", "Mann", email="vm2583@columbia.edu", role = "aut") )
# Description: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>). This package is for 'ggplot2' plotting methods for 'nlmixr2' objects.
# License: GPL (>= 3)
# URL: https://github.com/nlmixr2/nlmixr2plot
# BugReports: https://github.com/nlmixr2/nlmixr2plot/issues/
# Imports: ggplot2, nlmixr2est, nlmixr2extra, rxode2, utils, vpc, xgxr
# Suggests: testthat (>= 3.0.0), dplyr, withr, nlmixr2data
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.2.1
# NeedsCompilation: no
# Packaged: 2022-10-20 01:52:54 UTC; matt
# Author: Matthew Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Bill Denney [ctb] (<https://orcid.org/0000-0002-5759-428X>), Wenping Wang [aut], Vipul Mann [aut]
# Maintainer: Matthew Fidler <matthew.fidler@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-10-20 03:12:36 UTC
